image: node:11.6.0 

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - npm install 
    - npm install pm2 -g
    - pm2 kill
    - pm2 start app.js

  artifacts:
    paths:
      - ./
 

deploy_job:
  stage: deploy
  script:
    - echo Deploy OK
  only:
    - release
  when: manual